### ISSUE TITLE
GPU setup and training time

### ISSUE THREAD

**Issue by trumDog** [HalfSummer11/CAPTRA#3]
Hello, thank you for releasing such a wonderful work! 
Recently, I am reading this paper and learning the code, but I have several problems about the training setups.

1. What is the GPUs setup? and how long did does it take to train the NOCS dataset and the SAPIEN dataset respectively? I have tried to train the RotationNet using a 3090 GPU, however, it takes ~2 hours per category on the NOCS dataset. It seems to be very time-consuming.
2. What's the epoch setup of training CoordinateNet and RotationNet respectively on the two datasets?

**Comment by HalfSummer11** [comment]
Hi, thanks for your interest in our project :)
We train on a TITAN Xp. On NOCS dataset, a training epoch takes 1~2.5h depending on the category. On SAPIEN dataset,  a training epoch takes ~20min for CoordinateNet, 30~60min for RotationNet.
It takes ~30 epochs for RotationNet and ~20 epochs for CoordinateNet to train on NOCS dataset, but it's also category-dependent, since the amount of data in each category differs a lot. On SAPIEN dataset, we trained the two networks both for ~100 epochs.

**Comment by trumDog** [comment]
Thank you for your detailed response. This helps me a lot!

**Comment by CNJianLiu** [comment]
> Hello, thank you for releasing such a wonderful work! Recently, I am reading this paper and learning the code, but I have several problems about the training setups.
> 
> 1. What is the GPUs setup? and how long did does it take to train the NOCS dataset and the SAPIEN dataset respectively? I have tried to train the RotationNet using a 3090 GPU, however, it takes ~2 hours per category on the NOCS dataset. It seems to be very time-consuming.
> 2. What's the epoch setup of training CoordinateNet and RotationNet respectively on the two datasets?

Hi, have you used your training model for testing? Does the training model similar to the authors' pre-trained model?

**Comment by luzou-ustc** [comment]
你好，由于这个模型的训练时间太长了，我跑通之后就没有继续训练了，所以不知道结果是不是和论文报告的差不多
