### ISSUE TITLE
Camera Parameters

### ISSUE THREAD

**Issue by DC1991** [HalfSummer11/CAPTRA#5]
Hi, thanks for your work. I am wondering how to get the camera parameters of the BMVC dataset or how to get the segmentation mask of this BMVC dataset.

**Comment by HalfSummer11** [comment]
Hi, thanks for your interest in our work :) 
Camera intrinsics and segmentation masks are not available in the [original dataset](https://hci.iwr.uni-heidelberg.de/vislearn/iccv2015-articulation-challenge/). And we used the version generated by the authors of *Category-Level Articulated Object Pose Estimation (CVPR 2020, Oral)* ([project](https://articulated-pose.github.io/), [paper](https://arxiv.org/abs/1912.11913), [code](https://github.com/dragonlong/articulated-pose)). Using the ground-truth object models and poses, they rendered the object masks in PyBullet - with coarse camera intrinsics. They then manually adjusted the camera intrinsics so that the rendered masks matched the RGB-D images. Lastly, object masks are rendered using the refined camera intrinsics.

**Comment by DC1991** [comment]
I see, thanks

**Comment by dongho-Han** [comment]
Hello! Can I ask for the BMVC dataset and camera parameters to share? As original dataset(ICCV'15) and A-NCSH don't provide any datas, currently we can't test any of BMVC dataset..
